### ISSUE TITLE
could I get the code for poisson reconstruction?

### ISSUE THREAD

**Issue by TardisBlue2** [graphics-research-group/2D-To-3D-Medical-Image-Colorization#1]

**Comment by TardisBlue2** [comment]
and where did you get the mri volume and grayscale cyro volume for GAN training?

**Comment by aradhyamathur** [comment]
Hi, for the MRI Volume you may refer [here](https://www.nlm.nih.gov/research/visible/visible_human.html) . We also obtained the cryo volume from the same and then converted it to grayscale. We will soon share the poisson reconstruction code as well.

**Comment by TardisBlue2** [comment]
> Hi, for the MRI Volume you may refer [here](https://www.nlm.nih.gov/research/visible/visible_human.html) . We also obtained the cryo volume from the same and then converted it to grayscale. We will soon share the poisson reconstruction code as well.

Thanks for your replying! I do get the data of VHP. But I  iterate through the file and see that the data from VHP2.0(./Male-Images/Visible Human 2.0 - Peter Ratiu) is unpaired.
However, from the images shown in your paper it appears that your images have corresponding labels and original images.If it is convenient, I hope you could answer my doubts.

**Comment by aradhyamathur** [comment]
Hi, @csbbbv you can use this code to create the gray modality using Screened Poisson Equation [here](https://github.com/roimehrez/photorealism). Yes, the data is unpaired and therefore we performed registration using fiducial markers to align the MRI and the cryo volume. Slicer3D has several tools for registration.

**Comment by TardisBlue2** [comment]
Thanks!
